ARG RAY_TAG_VERSION="2.8.0-py310"
ARG FULL_BASE_IMAGE=rayproject/ray:"$RAY_TAG_VERSION"

FROM $FULL_BASE_IMAGE

RUN pip install onnxruntime-openvino qdrant-client huggingface_hub

COPY base/ base/
COPY face_detection/ face_detection/ 
COPY face_embedding/ face_embedding/
COPY neural_search/ neural_search/
COPY predictors/ predictors/
COPY processing/ processing/
COPY jobs/ .
COPY models/ models/